apiVersion: v1
kind: Service
metadata:
  name: goapp-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: replicaset-label